apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cross-namespace-ingress
  namespace: cilium-policy-demo
spec:
  endpointSelector:
    matchLabels:
      app: cross-namespace-server
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: cross-namespace-client
